### ISSUE TITLE
Example does not compile

### ISSUE THREAD

**Issue by Ryetschye** [summitto/pgp-packet-library#50]
I try to compile the 3rd example: Creating a PGP key from raw point data
I think there is one error:
`    std::vector<uint8_t> data;
    data.resize( ...
`
versus
`    std::vector<uint8_t> data
    data.resize( ...
`
And regarding the newest GSL version 3.x I receive the following error:
`/usr/local/include/pgp-packet/decoder.h:164:117: Fehler: »index_type« in »class gsl::span<unsigned char>«`
If I pull tag v2.1.0 it seems to be fine.

Furthermore I am not able to create the following instances:
`signature_creation_time_subpacket`
`key_expiration_time_subpacket`
`key_flags_subpacket`
Is it ok to write the following, e.g.:
`pgp::signature_subpacket::issuer_fingerprint`

**Comment by vicsn** [comment]
Thank you for noting. We'll update the README next week, in the meantime you can have a look at code examples from https://github.com/summitto/pgp-key-generation if you're stuck!

**Comment by bysnack** [comment]
I just merged https://github.com/summitto/pgp-packet-library/pull/51 and https://github.com/summitto/pgp-packet-library/pull/52

The README was updated with the correct examples and we now require GSL v3.0+ since the gsl::span interface was modified to satisfy the standard specification and some of the operations used by us are only available on an external file, more about this [here](https://devblogs.microsoft.com/cppblog/gsl-3-0-0-release/).

You should be able to run the examples with no further problems!
